<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
  <None Update=".env">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
</ItemGroup>

  <ItemGroup>
    <Compile Remove="Domain\DTOs\NewFolder1\**" />
    <Compile Remove="Domain\DTOs\NewFolder2\**" />
    <Compile Remove="Domain\DTOs\NewFolder\**" />
    <Content Remove="Domain\DTOs\NewFolder1\**" />
    <Content Remove="Domain\DTOs\NewFolder2\**" />
    <Content Remove="Domain\DTOs\NewFolder\**" />
    <EmbeddedResource Remove="Domain\DTOs\NewFolder1\**" />
    <EmbeddedResource Remove="Domain\DTOs\NewFolder2\**" />
    <EmbeddedResource Remove="Domain\DTOs\NewFolder\**" />
    <None Remove="Domain\DTOs\NewFolder1\**" />
    <None Remove="Domain\DTOs\NewFolder2\**" />
    <None Remove="Domain\DTOs\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Domain\DTOs\ProjectDTOs\CreateProjectRequestDTO.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="8.2.0" />
  </ItemGroup>

</Project>
